// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbpqluzodiulygkjpxip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRicHFsdXpvZGl1bHlna2pweGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTk4NjQsImV4cCI6MjA3Mjc5NTg2NH0.Jm4xHSZZgL8gJugs8hUSIxJU0u86p_i4WzQvySIuk-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});